openapi: 3.1.0
info:
  title: User API (Go-auth-jwt)
  version: 1.0.0
  description: API untuk mengelola user
  contact:
    name: Faiq
    email: faiqsr13@gmail.com
    url: https://github.com/FaiqSr
paths:
  /user:
    get:
      summary: get user information
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
             schema:
              example:
                message: "Berhasil mengambil data user"
                data :
                  id : 1
                  name: Faiq Subhi Ramadlan
                  email: faiqsr13@gmail.com
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "Jwt token not found or expired"
    
    put:
      summary: Update user information
      parameters:
        - in: body
          name: Name
          required: false
          schema:
            example:
              name: Faiq test
        - in: body
          name: Email
          required: false
          schema:
            example:
              email: faiqsr3@gmail.com
        - in: body
          name: password
          required: false
          schema:
            example:
              password: password
        - in: header
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
             schema:
              example:
                message: "Berhasil mengupdate informasi user"
                data :
                  id : 1
                  name: Faiq Test
                  email: faiqsr3@gmail.com
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "Jwt token not found or expired"
    delete:
      summary: Logout user
      responses:
        '200':
          description: OK
          content:
            application/json:
             schema:
              example:
                message: "Berhasil logout"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "Jwt token not found or expired"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            format: bearer
  /user/register:
    post:
      summary: Create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                name: Faiq Subhi Ramadlan
                email: faiqsr13@gmail.com
                password: password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  message: "Berhasil membuat user"
                  data :
                    id : 1
                    name: Faiq Subhi Ramadlan
                    email: faiqsr13@gmail.com
  /user/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                email: faiqsr13@gmail.com
                password: password  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  message: "Berhasil login"
                  data :
                    token: "Generated token"